    
#servier
server: 
  port: 8091
spring: 
  application: 
    name: wpf-template-client-ribbon

#regisrty eureka
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://127.0.0.1:8761/eureka/
      
wpf-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule