logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: debug
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0