server:
  port: 8031
spring:
  application:
    name: wpf-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  appConfig: wpf-template-client,wpf-template-client-feign-hystrix-fallback-stream
  clusterNameExpression: "'default'"